"""File for holding a list of all attachments for weapons - primary and secondary."""

from enum import Enum, auto

class Muzzles(Enum):
    # added for SVA 545 Assault Rifle
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    SHADOWSTRIKE_SUPPRESSOR = "SHADOWSTRIKE SUPPRESSOR"
    VT7_SPIRITFIRE_SUPPRESSOR = "VT-7 SPIRITFIRE SUPPRESSOR"
    HMRES_MOD_SUPPRESSOR = "HMRES MOD SUPPRESSOR"
    MONOLITHIC_SUPPRESSOR = "MONOLITHIC SUPPRESSOR"
    SONIC_SUPPRESSOR = "SONIC SUPPRESSOR"
    COLOSSUS_SUPPRESSOR = "COLOSSUS SUPPRESSOR"
    BROADHEAD_3DP = "BROADHEAD-3DP"
    SILENTFIRE_XG6 = "SILENTFIRE XG6"
    ECHOLINE_GSX = "ECHOLINE GS-X"
    ZULU_60 = "ZULU-60"
    HARBINGER_D20 = "HARBINGER D20"
    ECHOLESS_80 = "ECHOLESS-80"
    FSS_COVERT_V = "FSS COVERT V"
    GAUGE_9_MONO = "GUAGE-9 MONO"
    ELR_BLACKFIRE_COMPENSATOR = "ELR BLACKFIRE COMPENSATOR"
    WRATHGUARD_COMPENSATOR = "WRATHGUARD COMPENSATOR"
    T4LR_SABER_COMPENSATOR = "T4LR SABER COMPENSATOR"
    EX01_MATCH_COMPENSATOR = "EX-01 MATCH COMPENSATOR"
    T51R_BILLETED_BRAKE = "T51R BILLETED BRAKE"
    PURIFIER_MUZZLE_BRAKE = "PURIFIER MUZZLE BRAKE"
    CASUS_BRAKE = "CASUS BRAKE"
    ENDLESS_30_COMPENSATOR = "ENDLESS 30 COMPENSATOR"
    JAK_BFB = "JAK BFB"
    RF_CROWN_50 = "RF CROWN 50"
    KOMODO_HEAVY = "KOMODO HEAVY"
    XTEN_PORTED_290 = "XTEN PORTED 290"
    FJX_FULCRUM_PRO = "FJX FULCRUM PRO"
    CRONEN_OP44 = "CRONEN OP44"
    FTAC_CASTLE_COMP = "FTAC CASTLE COMP"
    XTEN_HAVOC_90 = "XTEN HAVOC 90"
    SAKIN_TREAD_40 = "SAKIN TREAD-40"
    S37C_DL_BREACHER_DEVICE = "S-37C DL BREACHER DEVICE"
    C400_DOOR_KNOCKER = "C400 DOOR KNOCKER"
    JCZ_390_MUZZLE_DEVICE = "JCZ-390 MUZZLE DEVICE"
    L4R_FLASH_HIDER = "L4R FLASH HIDER"
    CORVUS_SLASH_GEN2 = "CORVUS SLASH GEN. 2"
    CRONEN_MAW_86 = "CRONEN MAW-86"
    DARK_KX30 = "DARK KX30"
    VLK_KOLOSS_FLASH_HIDER = "VLK KOLOSS FLASH HIDER"
    STER45_SKYFURY_COMPENSATOR = "STER45 SKYFURY COMPENSATOR"
    ZEHMN35_COMPENSATED_FLASH_HIDER = "ZEHMN35 COMPENSATED FLASH HIDER"

    # added for Kastov762 Assault Rifle
    VT7_SPIRITFIRE_SUPPRESSOR_L = "VT-7 SPIRITFIRE SUPPRESSOR L"
    HMRES_MOD_SUPPRESSOR_L = "HMRES MOD SUPPRESSOR L"
    COLOSSUS_SUPPRESSOR_L = "COLOSSUS SUPPRESSOR L"
    BRUEN_HARMONIC_SUPPRESSOR_L = "BRUENEN HARMONIC SUPPRESSOR L"
    HUSHER_65_SILENCER = "HUSHER-65 SILENCER"
    FR_TITAN_SILENCER = "FR TITAN SILENCER"
    POLOARFIRE_S = "POLARFIRE-S"
    ZLR_TALON_5 = "ZLR TALON 5"
    KASTOVIA_DX90 = "KASTOVIA DX90"
    CRONEN_SPDR = "CRONEN SP-DR"
    STER45_SKYFURY_COMPENSATOR_L = "STER45 SKYFURY COMPENSATOR L"
    ELR_BLACKFIRE_COMPENSATOR_L = "ELR BLACKFIRE COMPENSATOR L"
    T4LR_SABER_COMPENSATOR_L = "T4LR SABER COMPENSATOR L"
    EX01_MATCH_COMPENSATOR_L = "EX-01 MATCH COMPENSATOR L"
    T51R_BILLETED_BRAKE_L = "T51R BILLETED BRAKE L"
    PURIFIER_MUZZLE_BRAKE_L = "PURIFIER MUZZLE BRAKE L"
    CASUS_BRAKE_L = "CASUS BRAKE L"
    TEMPUS_GH50 = "TEMPUS GH50"
    TY_LR8 = "TY-LR8"
    LOCKSHOT_KT85 = "LOCKSHOT KT85"
    SA_LEVELER_55 = "SA LEVELER 55"
    BORE_490 = "BORE-490"
    S37C_DL_BREACHER_DEVICE_L = "S-37C DL BREACHER DEVICE L"
    GL_CLEAR_BREACH = "GL CLAER BREACH"
    TA_HUL_BREACH_KL = "TL HUL-BREACH KL"
    EIGHT_POINT_FLASH_HIDER = "EIGHT-POINT FLASH HIDER"
    TZL_90_V3 = "TZL-90 V3"
    CRONEN_DARK_KX30 = "CRONEN DARK KX30"
    MONOLITHIC_SUPPRESSOR_L = "MONOLITHIC SUPPRESSOR L"
    SONIC_SUPPRESSOR_L = "SONIC SUPPRESSOR L"
    WRATHGUARD_COMPENSATOR_L = "WRATHGUARD COMPENSATOR L"

    # added for FTAC RECON Battle Rifle
    NILSOUND_90 = "NILSOUND 90"
    FTAC_DREADNOUGHT = "FTAC DREADNOUGHT"
    FTAC_REAPER = "FTAC REAPER"
    BRUEN_AGENT_90 = "BRUEN AGENT 90"
    TALON_SIXTEEN = "TALON SIXTEEN"
    EXF_RELENTLESS_40 = "EXF RELENTLESS-40"
    BVM_338 = "BVM-338"
    CRONEN_DM338 = "CRONEN DM338"
    SHRED_CP90 = "SHRED CP90"
    XRK_KRAKEN = "XRK KRAKEN"
    TA_CG76 = "TA CG76"
    AP_390_FLASH_HIDER = "AP-390 FLASH HIDER"
    PORTED_DZ38 = "PORTED DZ38"
    DARK_KX50_FLASH_HIDER = "DARK KX50 FLASH HIDER"
    DEMON_HELIX_T7 = "DEMON HELIX T7"
    SHADOWSTRIKE_SUPPRESSOR_L = "SHADOWSTRIKE SUPPRESSOR L"

    # added for STIKER SMG
    SHADOWSTRIKE_SUPPRESSOR_S = "SHADOWSTRIKE SUPPRESSOR S"
    HMRES_MOD_SUPPRESSOR_S = "HMRES MOD SUPPRESSOR S"
    MONOLITHIC_SUPPRESSOR_S = "MONOLITHIC SUPPRESSOR S"
    COLOSSUS_SUPPRESSOR_S = "COLOSSUS SUPPRESSOR S"
    XTEN_RR_40 = "XTEN RP-40"
    FORGE_DX90_F = "FORGE DX90-F"
    SA_SCHALLDAMPFER_99 = "SA SCHALLDAMPFER 99"
    SINGUARD_MKV = "SINGUARD MKV"
    EXF_HUNTRESS_90 = "EXF HUNTRESS 90"
    XTEN_BLACK_KITE = "XTEN BLACK KITE"
    FSS_COVERT_IV = "FSS COVERT IV"
    STER45_SKYFURY_COMPENSATOR_S = "STER45 SKYFURY COMPENSATOR S"
    ELR_BLACKFIRE_COMPENSATOR_S = "ELR BLACKFIRE COMPENSATOR S"
    T4LR_SABER_COMPENSATOR_S = "T4LR SABER COMPENSATOR S"
    PURIFIER_MUZZLE_BRAKE_S = "PURIFIER MUZZLE BRAKE S"
    BRUEN_PENDULUM = "BRUEN PENDULUM"
    AVR_T90_COMP = "AVR-T90 COMP"
    LACERTA_COMPENSATOR = "LACERTA COMPENSATOR"
    XTEN_RAZOR_COMP = "XTEN_RAZOR_COMP"
    XRK_SANDSTORM = "XRK_SANDSTORM"
    BRUEN_CUBIC_COMP = "BRUEN CUBIC COMP"
    XRK_KNOCKOUT_BREACH = "XRK KNOCKOUT BREACH"
    TA_HUL_BREACH = "TL HUL-BREACH"
    SPIRAL_V3p5_FLASH_HIDER = "SPIRAL V3.5 FLASH HIDER"
    FOX_202_FLASH_HIDER = "FOX-202 FLASH HIDER"
    SONIC_SUPPRESSOR_S = "SONIC SUPPRESSOR S"
    WRATHGUARD_COMPENSATOR_S = "WRATHGUARD COMPENSATOR S"
    T51R_BILLETED_BRAKE_S = "T51R BILLETED BRAKE S"
    VP27_MINI_BRAKE_S = "VP27 MINI BRAKE S"
    S37C_DL_BREACHER_DEVICE_S = "S-37C DL BREACHER DEVICE S"

    # added for FENNEC SMG
    SHIKRA_SILENCER = "SHIKRA SILENCER"

    # added for LOCKWOOD 680 shotgun
    TECTONICA_SUPPRESSOR = "TECTONICA SUPPRESSOR"
    SA_SCHWEIGEN_DX = "SA SCHWEIGEN DX"
    SA_SCHWEIGEN_XS = "SA SCHWEIGEN XS"
    FTAC_TRIDENTCORE = "FTAC TRIDENTCORE"
    SA_MX_50 = "SA MX-50"
    DR_77_IRONHEAD_BRAKE = "DR-77 IRONHEAD BRAKE"
    SR70_TAQ_BRAKE = "SR70 TAQ BRAKE"
    RMGE_7 = "RMGE-7"
    LOCKWOOD_SMOOTHFIRE_12 = "LOCKWOOD SMOOTHFIRE 12"
    OVL_70_COMP = "OVL-70 COMP"
    VULTURE_CLAW_BREACHER = "VULTURE CLAW BREACHER"
    MACK8_FROST_BITE = "MACK8 FROST BITE"
    CROWN_BREAKER_CHOKE = "CROWN BREAKER CHOKE"
    XTEN_FULL_CHOKE = "XTEN FULL CHOKE"
    XTEN_MODIFIED_CHOKE = "XTEN MODIFIED CHOKE"
    BRYSON_IMPROVED_CHOKE = "BRYSON IMPROVED CHOKE"
    BRYSON_CHOKE = "BRYSON CHOKE"
    FLASH_TWIST_90 = "FLASH TWIST-90"
    XTEN_QUADFLASH = "XTEN QUADFLASH"
    FSS_THUNDERSTRIKE_BRAKE = "FSS THUNDERSTRIKE BRAKE"

    # added for LOCKWOOD 300 shotgun
    SAKIN_DB107 = "SAKIN DB107"
    TEMPUS_VOX = "TEMPUS VOX"
    GW_MAX_99 = "GW MAx-99"
    DB_BIG_BORE_COMP = "DB-BIG BORE COMP"
    DB_DREAD_COMP = "DB-DREAD COMP"
    MACK8_SHOTGUN_BREACH = "MACK8 SHOTGUN BREACH"
    XTEN_V1p3_CHOKE = "XTEN V1.3 CHOKE"
    BRYSON_SERIES_XII_CHOKE = "BRYSON SERIES XII CHOKE"
    RECKONER_COMP = "RECKONER COMP"
    XTEN_V2p0_CHOKE = "XTEN V2.0 CHOKE"
    BRYSON_SERIES_IX_CHOKE = "BRYSON SERIES IX CHOKE"

    # added for EXPEDITE 12 Shotgun
    LONG_HAUL_50 = "LONG HAUL 50"
    WOLFCALL_300 = "WOLFCALL 300"

    # added for XRK STALKER Sniper Rifle
    SA_SHROUD_FLASH_HIDER = "SA SHROUD FLASH HIDER"
    DEMON_HELIX_XL = "DEMON HELIX XL"
    VT7_SPIRITFIRE_SUPPRESSOR_XL = "VT-7 SPIRITFIRE SUPPRESSOR XL"
    XRK_NIGHTFALL_SUPPRESSOR_XL = "XRK NIGHTFALL SUPPRESSOR XL"
    MONOLITHIC_SUPPRESSOR_XL = "MONOLITHIC SUPPRESSOR XL"
    SONIC_SUPPRESSOR_XL = "SONIC SUPPRESSOR XL"
    COLOSSUS_SUPPRESSOR_XL = "COLOSSUS SUPPRESSOR XL"
    BRUEN_L40_KOBRA = "BRUEN L40 KOBRA"
    TALON_SIXTEEN_SILENCER = "TALON SIXTEEN SILENCER"
    NILSOUND_90_SILENCER = "NILSOUND 90 SILENCER"
    BRUEN_COUNTER_OPS = "BRUEN COUNTER OPS"
    STER45_SKYFURY_COMPENSATOR_XL = "STER45 SKYFURY COMPENSATOR XL"
    ELR_BLACKFIRE_COMPENSATOR_XL = "ELR BLACKFIRE COMPENSATOR XL"
    CASUS_BRAKE_XL = "CASUS BRAKE XL"
    MV50_MUZZLE_BRAKE = "MV50 MUZZLE BRAKE"
    H26_PORTED_COMP = "H26 PORTED COMP"
    VIGILANTE_COMP = "VIGILANTE COMP"
    LEGION_FIRE_COMP = "LEGION FIRE COMP"
    MAMMOTH_50_SUPPRESSOR = "MAMMOTH 50 SUPPRESSOR"

    # added for COR-45 Handgun
    HMRES_MOD_SUPPRESSOR_XS = "HMRES MOD SUPPRESSOR XS"
    MONOLITHIC_SUPPRESSOR_XS = "MONOLITHIC SUPPRESSOR XS"
    SONIC_SUPPRESSOR_XS = "SONIC SUPPRESSOR XS"
    COLOSSUS_SUPPRESSOR_XS = "COLOSSUS SUPPRESSOR XS"
    CN30_SUPPRESSOR = "CN30 SUPPRESSOR"
    FT_STEEL_FIRE = "FT STEEL FIRE"
    FORGE_DX30_S = "FORGE DX30-S"
    DZS_OPEN_COMP = "DZS OPEN COMP"
    SLAB_10_COMP = "SLAB-10 COMP"
    XRK_VENTOR_900 = "XRK VENTOR-900"
    COMP_905F_PISTOL = "COMP 905F PISTOL"
    BRUEN_TRI_PORT = "BRUEN TRI-PORT"
    CORVUS_SERIES_D = "CORVUS SERIES-D"
    HOLE_PUNCHER_BREACHER = "HOLE PUNCHER BREACHER"
    XRK_QZ_105 = "XRK QZ-105"
    SA_GF90_FLASH_HIDER = "SA GF90 FLASH HIDER"
    STER45_SKYFURY_COMPENSATOR_XS = "STER45 SKYFURY COMPENSATOR XS"
    ELR_BLACKFIRE_COMPENSATOR_XS = "ELR BLACKFIRE COMPENSATOR XS"
    VP27_MINI_BRAKE_XS = "VP27 MINI BRAKE XS"
    
    # added for GS .50 Handgun
    EXF_FIFTY_GS = "EXF FIFTY FS"
    MATUZEK_CROWN = "MATUZEK CROWN"
    FTAC_FIFTY_COMP = "FTAC FIFTY COMP"
    POTATO_MASHER = "POTATO MASHER"
    SA_PEAK_77 = "SA PEAK-77"
    GW_FLASH_FIFTY = "GW FLASH FIFTY"

    # added for BASILISK Handgun
    RVS607_COMPENSATOR = "RVS607 COMPENSATOR"
    FSS_KL30 = "FSS KL30"
    FTAC_H50_PORTED = "FTAC H50 PORTED"
    FSS_VMW_FLASH_HIDER = "FSS VMW FLASH HIDER"

    # added for FTAC SIEGE Handgun
    FTAC_SIEGE_CONTROL = "FTAC SIEGE CONTROL"

class Barrels(Enum):
    pass

class Arms(Enum):
    pass

class Lasers(Enum):
    # added for SVA 545 Assault Rifle
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    SL_RAZORHAWK_LASER_LIGHT = "SL RAZORHAWK LASER LIGHT"
    CS15_SCARLET_BOX_LASER = "CS15 SCARLET BOX LASER"
    PRO_SAPPHIRE_BOX_LASER = "PRO SAPPHIRE BOX LASER"
    VERDANT_HOOK_BOX_LASER = "VERDANT HOOK BOX LASER"
    SZ_1MW_PEQ = "SZ 1MW PEQ"
    SCHLAGER_PEQ_BOX_IV = "SCHLAGER PEQ BOX IV"
    CORIO_LAZ_44_V3 = "CORIO LAZ-44 V3"
    FSS_OLE_V_LASER = "FSS OLE-V LASER"
    CANTED_VIBRO_DOT_7 = "CANTED_VIBRO_DOT_7"
    LASER_BOX_1MW = "1MW LASER BOX"
    STOVL_DR_LASER_BOX = "STOVL DR LASER BOX"
    CORVUS_PEQ_BEAM_5 = "CORVUS PEQ BEAM-5"
    FTAC_GRIMLINE_LASER = "FTAC GRIMLINE LASER"
    LUMINATE_44 = "LUMINATE-44"
    DXS_FLASH_90 = "DXS FLASH 90"

    # added for STB556 Assault Rifle
    CS15_SCARLET_CYLINDRICAL_LASER = "CS15 SCARLET CYLINDRICAL LASER"
    PRO_SAPPHIRE_CYLINDRICAL_LASER = "PRO SAPPHIRE CYLINDRICAL LASER"
    VERDANT_HOOK_CYLINDRICAL_LASER = "VERDANT HOOK CYLINDRICAL LASER"
    ARTEMIS_LASER_1MW = "1MW ARTEMIS LASER"
    QUICK_FIRE_LASER_1MW = "1MW QUICK FIRE LASER"
    ACCU_SHOT_5MW_LASER = "ACCU-SHOT 5MW LASER"
    VLK_LZR_7MW = "VLK LZR 7MW"
    CANTED_LASER_7MW = "7MW CANTED LASER"
    SCHLAGER_ULO_66_LASER = "SCHLAGER ULO-66 LASER"
    STOVL_TAC_LASER = "STOVL TAC LASER"
    HIPSHOT_L20 = "HIPSHOT L20"
    POINT_G3P_04 = "POINT-G3P 04"
    FJX_ULTRABEAM_XR = "FJX ULTRABEAM XR"
    EXF_SOLARFLARE = "EXF SOLARFLARE"
    KIMURA_RYL33_LASER_LIGHT = "KIMURA RYL33 LASER LIGHT"

    # added for COR45 Handgun
    KR_HX_15_LASER_LIGHT = "KR HX-15 LASER LIGHT"
    PRO_SAPPHIRE_MOUNTED_LASER = "PRO SAPPHIRE MOUNTED LASER"
    VERDANT_HOOK_MOUNTED_LASER = "VERDANT HOOK MOUNTED LASER"
    SERIES_710_PISTOL_LASER = "SERIES 710 PISTOL LASER"
    FJX_DIOD_70 = "FJX DIOD-70"
    XTEN_SIDEARM_L400 = "XTEN SIDEARM-L400"
    PISTOL_LASER_1MW = "1MW PISTOL LASER"
    DZM_1000_L = "DZM-1000 L"
    FTAC_VORTEX_200 = "FTAC VORTEX 200"
    CS15_SCARLET_MOUNTED_LASER = "CS15 SCARLET MOUNTED LASER"

    # added for BASILISK handgun
    BASILISK_GRIP_LASER = "BASILISK GRIP LASER"
    REVO_LSD_7MW = "REVO-LSD 7MW"
    CORVUS_LZR_790 = "CORVUS LZR-790"

class Optics(Enum):
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    KR_INTLAS_LSJ_3 = "KR INTLAS LSJ-3"
    CRONEN_IRONS = "CRONEN IRONS"
    SLATE_REFLECTOR = "SLATE REFLECTOR"
    JAK_BULLSEYE = "JAK BULLSEYE" 
    SLIMLINE_PRO = "SLIMLINE PRO"
    SZ_MINI = "SZ MINI"
    CRONEN_MINI_DOT = "CRONEN MINI DOT"
    CRONEN_MINI_PRO = "CRONEN MINI PRO"
    SZ_SIGMA_IV_OPTIC = "SZ SIGMA-IV OPTIC"
    SZ_MINITAC_40 = "SZ_MINITAC-40"
    KR_MINITAC_40_RISER = "KR MINITAC-40 RISER"
    QTG_REFLEX_SIGHT = "QTG REFLEX SIGHT"
    CAUCASUS_REFLEX_SIGHT = "CAUCASUS REFLEX SIGHT"
    MK3_REFLECTOR = "MK. 3 REFLECTOR"
    DRAGONS_EYE_OPTIC = "DRAGONS' EYE OPTIC"
    RHINO_REFLEX = "RHINO REFLEX"
    XRK_ON_POINT_OPTIC = "XRK ON-POINT OPTIC"
    AIM_OP_V4 = "AIM OP-V4"
    DF105_REFLEX_SIGHT = "DF105 REFLEX SIGHT"
    MONOCLE_CT90 = "MONOCLE CT90"
    CORVUS_SOL_76 = "CORVUS SOL-76"
    SZ_RECHARGE_DX = "SZ RECHARGE-DX"
    SZ_SRO_7 = "SZ SRO-7"
    CORIO_RE_X_PRO = "CORIO RE-X PRO"
    CHRIOS_HOLO = "CHRIOS HOLO"
    CORIO_ENFORCER_OPTIC = "CORIO ENFORCER OPTIC"
    SZ_LONEWOLF_OPTIC = "SZ LONEWOLF OPTIC"
    KAZAN_HOLO = "KAZAN-HOLO"
    SZ_BATTLE_OPTIC = "SZ BATTLE OPTIC"
    CORVUS_DOWNRANGE_00 = "CORVUS DOWNRANGE-00"
    XTEN_ANGEL_40 = "XTEN ANGEL-40"
    SZ_HOLOTHERM = "SZ HOLOTHERM"
    CORIO_ELT_10_2p5 = "CORIO ELT-10 2.5"
    KR_MORTIS_PRECISION_2p5X = "KR MORTIS PRECISION 2.5X"
    SL_TRUESIGHT_2p5X = "SL TRUESIGHT 2.5X"
    KR_MARAUDER_9_RISER = "KR MARAUDER 9 RISER"
    TOS_NIGHTFALL_2p5X_THERMAL_OPTIC = "TOS NIGHTFALL 2.5X THERMAL OPTIC"
    AOK_4p0X_RQ_9_RECON = "AOK 4.0X RQ-9 RECON"
    TX4_HAVOC = "TX4 HAVOC"
    VLK_4p0_OPTIC = "VLK 4.0 OPTIC"
    SCHLAGER_3p4X = "SCHLAGER 3.4X"
    FORGE_TAC_DELTA_4 = "FORGE TAC DELTA 4"
    CRONEN_ZERO_P_OPTIC = "CRONEN ZERO-P OPTIC"
    SZ_BULLSEYE_OPTIC = "SZ BULLSEYE OPTIC"
    SZ_AGGRESSOR_IR_OPTIC = "SZ AGGRESSOR-IR OPTIC"
    SCHLAGER_NIGHT_VIEW = "SCHLAGER NIGHT VIEW"
    VX350_THERMAL_OPTIC = "VX350 THERMAL OPTIC"
    TEPLO_OP3_SCOPE = "TEPLO-OP3 SCOPE"
    HEINRICHTER_HYBRID_SCOPE = "HEINRICHTER HYBRID SCOPE"
    CORVUS_GHOSTVIEW = "CORVUS GHOSTVIEW"
    DR582_HYBRID_SIGHT = "DR582 HYBRID SIGHT"
    HYBRID_FIREPOINT = "HYBRID FIREPOINT"
    SZ_VOREX_90 = "SZ VOREX-90"
    BPZ40_HYBRID = "BPZ40 HYBRID"
    SZ_OSCAR_9 = "SZ OSCAR-9"
    ANGEL_40_4p8X = "ANGEL-40 4.8X"
    THERMO_OPTIC_X9 = "THERMO-OPTIC X9"
    TEPLO_CLEAR_SHOT = "TEPLO CLEAR SHOT"
    CORIO_CQC_SCOPE = "CORIO CQC SCOPE"
    DAUNT_C80 = "DAUNT-C80"
    FTAC_CHARLIE7 = "FTAC CHARLIE7"
    HMW_20_OPTIC = "HMW-20 OPTIC"
    LUCA_BANDERA_SCOPE = "LUCA BANDERA SCOPE"
    DS_FARSIGHT_11 = "DS FARSIGHT 11"
    RFL_OPTIC_3X = "3X RFL-OPTIC"
    DXS_CORIOLIS_V4 = "DXS CORIOLIS V4"
    LACHMANN_IMPACT_9 = "LACHMANN IMPACT 9"
    SPX_80_6p6X = "SP-X 80 6.6X"
    FTAC_LOCUS_SP = "FTAC LOCUS SP"
    LUCA_FIELD_6 = "LUCA FIELD-6"
    SZ_HEATSOURCE_800 = "SZ HEATSOURCE 800"
    HURRICANE_9_VARIABLE_OPTIC = "HURRICANE 9 VARIABLE OPTIC"
    SZ_ULTRA_11p5X = "SZ ULTRA 11.5X"
    MCPR_300_9p5X = "MCPR-300 9.5X"
    VICTUS_13X = "VICTUS 13X"
    IMPERIUM_12X = "IMPERIUM 12X"
    CARRACK_p300_11X = "CARRACK .300 11X"
    AKALINA_LR_STALK_OPTIC = "AKALINA LR-STALK OPTIC"
    KR_KATT_50_8X_SCOPE = "KR KATT-50 8X SCOPE"
    SHORT_ZOOM_6X_OPTIC = "6X SHORT-ZOOM OPTIC"
    SIGNAL_50_8X = "SIGNAL 50 8X"
    CORIO_13X_VRS = "CORIO 13X VRS"
    CORIO_SZ_HS_800 = "CORIO SZ-HS 800"
    RAPTOR_FVM40 = "RAPTOR-FVM40"
    DREXSOM_PRIME_90 = "DREXSOM PRIME-90"
    ARES_CLEAR_SHOT = "ARES CLEAR SHOT"
    SIGHTMAX_CLEAR_SHOT = "SIGHTMAX CLEAR SHOT"
    VIGILANT_30_C_IRON = "VIGILANT-30 C-IRON"
    LUCA_CANIS_4X_OPTIC = "LUCA CANIS 4X OPTIC"
    CORIO_RV500_OPTIC = "CORIO RV500 OPTIC"
    XTEN_ERX_10_MINI = "XTEN ERX-10 MINI"
    FSS_SPECTRE_MICROTHERM = "FSS SPECTRE MICROTHERM"
    NYDAR_MODEL_2023 = "NYDAR MODEL 2023"
    KR_V4_1X_RISER = "KR V4 1X RISER"
    TPS_INCENDIO_REFLEX = "TPS INCENDIO REFLEX"
    CORIO_EAGLESEYE_2p5X = "CORIO EAGLESEYE 2.5X",
    DEMONIC_CALL = "DEMOIC CALL"
    SZ_HM5_PRECISION_HYBRID_OPTIC = "SZ HM5 PRECISION HYBRID OPTIC"
    JOURNEYMAN_32_SCOPE = "JOURNEYMAN-32 SCOPE"
    CARRACK_6p3X_14X = "6.3X-14X CARRACK"
    HOUNDEYE_INTEGRATED_OPTIC = "HOUNDEYE INTEGRATED OPTIC"
    CRONEN_INTLAS_MSP_12 = "CRONEN INTLAS MSP-12"
    INTLAS_CAS_14 = "INTLAS CAS-14"

class Stocks(Enum):
    pass

class Combs(Enum):
    pass

class Guards(Enum):
    pass

class Bolts(Enum):
    pass

class RearGrips(Enum):
    pass

class TriggerActions(Enum):
    pass

class Magazines(Enum):
    pass

class Wires(Enum):
    STRAND_28_CABLE = "28 STRAND CABLE"
    STRAND_16_CABLE = "16 STRAND CABLE"

class AmmoTypes(Enum):
    FRANGIBLE = auto()
    HOLLOWPOINT = auto()
    TRACER = auto()
    ARMOR_PIERCING = auto()
    OVERPRESSURE_P = auto()
    INCENDIARY = auto()
    LOW_GRAIN_ROUNDS = auto()
    HIGH_GRAIN_ROUNDS = auto()
    HIGH_VELOCITY = auto()
    ROUND_NOSE = auto()
    MONO = auto()
    HARDENED = auto()
    AUTO_AET = auto()
    EXPLOSIVE = auto()
    SPIRE_POINT = auto()
    BALL = auto()
    SLUG = auto()
    SNAKESHOT = auto()

class Underbarrels(Enum):
    # added for SVA 545 Assault Rifle
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    JAK_PURIFIER = "JAK PURIFIER"
    XRK_EDGE_BW_4_HANDSTOP = "XRK EDGE BW-4 HANDSTOP"
    FTAC_MSP_98_HANDSTOP = "FTAC MSP-98 HANDSTOP"
    DR_6_HANDSTOP = "DR-6 HANDSTOP"
    XTEN_PHANTOM_5_HANDSTOP = "XTEN PHANTOM-5 HANDSTOP"
    XTEN_TX_12_HANDSTOP = "XTEN TX-12 HANDSTOP"
    FTAC_RS_9_STEALTH_ANGLED_GRIP = "FTAC RS-9 STEALTH ANGLED GRIP"
    BRUEN_BASTION_ANGLED_GRIP = "BRUEN BASTION ANGLED GRIP"
    CHEWK_ANGLED_GRIP = "CHEWK ANGLED GRIP"
    COMMANDO_FOREGRIP = "COMMANDO FOREGRIP"
    EDGE_47_GRIP = "EDGE-47 GRIP"
    DEMO_FIRM_GRIP = "DEMO FIRM GRIP"
    XTEN_GRAVEDIGGER = "XTEN GRAVEDIGGER"
    FTAC_RIPPER_56 = "FTAC RIPPER 56"
    DEMO_CLEANSHOT_40 = "DEMO CLEANSHOT 40"
    DEMO_IMP_44_GRIP = "DEMO IMP-44 GRIP"
    FTAC_TIGER_GRIP = "FTAC TIGER GRIP"
    FSS_SHARKFIN_90 = "FSS SHARKFIN 90"
    AGENT_GRIP = "AGENT GRIP"
    BRUEN_SYNC_SHOT_GRIP = "BRUEN SYNC SHOT GRIP"
    XTEN_DROP_GRIP = "XTEN DROP GRIP"
    XTEN_NEXUS_GRIP = "XTEN NEXUS GRIP"
    PHASE_3_GRIP = "PHASE-3 GRIP"
    BRUEN_HEAVY_SUPPORT_GRIP = "BRUEN HEAVY SUPPORT GRIP"
    KIMURA_RYN_03_VERTICAL_GRIP = "KIMURA RYN-03 VERTICAL GRIP"
    SL_SKELETAL_VERTICAL_GRIP = "SL SKELETAL VERTICAL GRIP"
    HOLGER_VERTICAL_GRIP = "HOLGER VERTICAL GRIP"
    BRUEN_TACTICAL_VERTICAL_GRIP = "BRUEN TACTICAL VERTICAL GRIP"
    BRUEN_PIVOT_VERTICAL_GRIP = "BRUEN PIVOT VERTICAL GRIP"
    MERC_FOREGRIP = "MERC FOREGRIP"
    LOCKGRIP_PRECISION_40 = "LOCKGRIP PRECISION-40"
    HEX_40_GRIP = "HEX-40 GRIP"
    SCHLAGER_TANGO = "SCHLAGER TANGO"
    VX_PINEAPPLE = "VX PINEAPPLE"
    OP_X9_FOREGRIP = "OP-X9 FOREGRIP"
    OPERATOR_FOREGRIP = "OPERATOR FOREGRIP"
    TV_WRECKER_GRIP = "TV WRECKER GRIP"
    BRUEN_TILT_GRIP = "BRUEN TILT GRIP"
    CRONEN_GROOVESHOT_GRIP = "CRONEN GROOVESHOT GRIP"
    EXF_BACKDRAFT_GRIP = "EXF BACKDRAFT GRIP"
    BRUEN_WARRIOR_GRIP = "BRUEN WARRIOR GRIP"
    BIPOD_V9_GRIP = "BIPOD V9 GRIP"
    CORE_BP2 = "CORE BP2"
    LEVEL_AIM_BIPOD = "LEVEL AIM BIPOD"
    CORNERSTONE_BIPOD = "CORNERSTONE BIPOD"
    XTEN_STABLE_SHOT = "XTEN STABLE SHOT"
    KL40_M2 = "KL40-M2"
    BURROW_500_DRILL_CHARGE = "BURROW 500 DRILL CHARGE"
    CORVUS_MASTERKEY = "CORVUS MASTERKEY"
    FTAC_SP_10_ANGLED_GRIP = "FTAC SP-10 ANGLED GRIP"
    KIMURA_SERAPHIC_VERTICAL_GRIP = "KIMURA SERAPHIC VERTICAL GRIP"
    CORVUS_TORCH = "CORVUS TORCH"

    # added for RAM-7 Assault Rifle
    SPW_40MM_HE = "SPW 40MM HE"
    SPW_40MM_DRILL = "SPW 40MM DRILL"
    
    # added for DG-56 Assault Rifle
    TTL_GS_40 = "TTL-GS 40"

    # added for FR AVANCER Assault Rifle
    FR_AVANCER_BIPOD = "FR AVANCER BIPOD"
    TL40_FIRE_DRAKE = "TL40 FIRE DRAKE"
    TL40_DRILL = "TL40 DRILL"

    # added for TAQ-56 Assault Rifle
    HELLSCREAM_40MM = "HELLSCREAM 40MM"
    HELLSCREAM_40MM_DRILL = "HELLSCREAM 40MM DRILL"

    # added for KASTOV762 Assault Rifle
    KL40_M2_DRILL = "KL40-M2 DRILL"

    # added for TEMPUS RAZORBACK Assault Rifle
    DM_PROTO_GRIP = "DM PROTO-GRIP"

    # added for WSP SWARM
    WSP_VENOM_GRIP = "WSP VENOM GRIP"
    WSP_LIBERATOR_INTEGRATED_FOREGRIP = "WSP LIBERATOR INTEGRATED FOREGRIP"

    # added for TAQ EVOLVERE LMG
    DI_GRIP_4p5 = "DI-GRIP 4.5"
    HOUND_9G_GRIP = "HOUND-9G GRIP"
    BO52_GRIP = "BO52 GRIP"

    # added for PULEMYOT LMG
    PULEMYOT_BIPOD = "PULEMYOT BIPOD"

    # added for BRUEN MK9 LMG
    BRUEN_MK9_BIPOD = "BRUEN MK9 BIPOD"

    # added for SAKIN LMG
    SAKIN_SIDE_GRIP = "SAKIN SIDE GRIP"
    CRONEN_WL55 = "CRONEN WL55"
    BRUEN_WARRIOR_LMG = "BRUEN WARRIOR LMG"
    SOSHKI = "SOSHKI"

    # added for RAAL LMG
    DEMO_NARROW_GRIP = "DEMO NARROW GRIP"
    XRK_DUNE_GRIP = "XRK DUNE GRIP"
    SA_SIDE_GRIP = "SA SIDE GRIP"
    RAAL_BIPOD = "RAAL BIPOD"

    # added for HCR LMG
    BRUEN_HEAVY_BIPOD = "BRUEN HEAVY BIPOD"

    # added for RPK LMG
    RPK_BIPOD = "RPK BIPOD"

    # added for FTAC SIEGE Handgun
    REBEL_HX = "REBEL-HX"
    S40_H_GRIP = "S40-H GRIP"
    WEDGE_GRIP = "WEDGE GRIP"

class CarryHandles(Enum):
    # added for FJX IMPERIUM Sniper Rifle
    FIELD_WRAPPED_HANDLE = "FIELD-WRAPPED HANDLE"
    KEYSTONE_HANDLE = "KEYSTONE HANDLE"






# class Attachments(Enum):
#     MUZZLES = Muzzles
#     BARRELS = Barrels
#     LASERS = Lasers
#     OPTICS = Optics
#     STOCKS = Stocks
#     COMBS = Combs
#     BOLTS = Bolts
#     REAR_GRIPS = RearGrips
#     TRIGGER_ACTIONS = TriggerActions
#     MAGAZINES = Magazines
#     AMMO_TYPES = AmmoTypes
#     UNDERBARRELS = Underbarrels
#     GUARDS = Guards