"""File for holding a list of all attachments for weapons - primary and secondary."""

from enum import Enum, auto

class AmmoTypes(Enum):
    FRANGIBLE = auto()
    HOLLOWPOINT = auto()
    TRACER = auto()
    ARMOR_PIERCING = auto()
    OVERPRESSURE_P = auto()
    INCENDIARY = auto()
    LOW_GRAIN_ROUNDS = auto()
    HIGH_GRAIN_ROUNDS = auto()
    HIGH_VELOCITY = auto()
    ROUND_NOSE = auto()
    MONO = auto()
    HARDENED = auto()
    AUTO_AET = auto()
    EXPLOSIVE = auto()
    SPIRE_POINT = auto()
    BALL = auto()
    SLUG = auto()
    SNAKESHOT = auto()

class Barrels(Enum):
    pass

class Bolts(Enum):
    pass

class Combs(Enum):
    pass

class Guards(Enum):
    pass

class Lasers(Enum):
    pass

class Magazines(Enum):
    pass

class Muzzles(Enum):
    SHADOWSTRIKE_SUPPRESSOR_S = "SHADOWSTRIKE SUPPRESSOR S"
    SHADOWSTRIKE_SUPPRESSOR = "SHADOWSTRIKE SUPPRESSOR"
    SHADOWSTRIKE_SUPPRESSOR_L = "SHADOWSTRIKE SUPPRESSOR L"
    HMRES_MOD_SUPPRESSOR_S = "HMRES MOD SUPPRESSOR S"
    HMRES_MOD_SUPPRESSOR = "HMRES MOD SUPPRESSOR"
    HMRES_MOD_SUPPRESSOR_L = "HMRES MOD SUPPRESSOR L"
    MONOLITHIC_SUPPRESSOR_S = "MONOLITHIC SUPPRESSOR S"
    MONOLITHIC_SUPPRESSOR = "MONOLITHIC SUPPRESSOR"
    MONOLITHIC_SUPPRESSOR_L = "MONOLITHIC SUPPRESSOR L"
    COLOSSUS_SUPPRESSOR_S = "COLOSSUS SUPPRESSOR S"
    COLOSSUS_SUPPRESSOR = "COLOSSUS SUPPRESSOR"
    COLOSSUS_SUPPRESSOR_L = "COLOSSUS SUPPRESSOR L"
    STER45_SKYFURY_COMPENSATOR_S = "STER45 SKYFURY COMPENSATOR S"
    STER45_SKYFURY_COMPENSATOR = "STER45 SKYFURY COMPENSATOR"
    STER45_SKYFURY_COMPENSATOR_L = "STER45 SKYFURY COMPENSATOR L"
    ELR_BLACKFIRE_COMPENSATOR_S = "ELR BLACKFIRE COMPENSATOR S"
    ELR_BLACKFIRE_COMPENSATOR = "ELR BLACKFIRE COMPENSATOR"
    ELR_BLACKFIRE_COMPENSATOR_L = "ELR BLACKFIRE COMPENSATOR L"
    T4LR_SABER_COMPENSATOR_S = "T4LR SABER COMPENSATOR S"
    T4LR_SABER_COMPENSATOR = "T4LR SABER COMPENSATOR"
    T4LR_SABER_COMPENSATOR_L = "T4LR SABER COMPENSATOR L"
    PURIFIER_MUZZLE_BREAK_S = "PURIFIER MUZZLE BRAKE S"
    PURIFIER_MUZZLE_BREAK = "PURIFIER MUZZLE BRAKE"
    PURIFIER_MUZZLE_BREAK_L = "PURIFIER MUZZLE BRAKE L"
    SONIC_SUPPRESSOR_S = "SONIC SUPPRESSOR S"
    SONIC_SUPPRESSOR = "SONIC SUPPRESSOR"
    SONIC_SUPPRESSOR_L = "SONIC SUPPRESSOR L"
    WRATHGUARD_COMPENSATOR_S = "WRATHGUARD COMPENSATOR S"
    WRATHGUARD_COMPENSATOR = "WRATHGUARD COMPENSATOR"
    WRATHGUARD_COMPENSATOR_L = "WRATHGUARD COMPENSATOR L"
    T51R_BILLETED_BREAK_S = "T51R BILLETED BRAKE S"
    T51R_BILLETED_BREAK = "T51R BILLETED BRAKE"
    T51R_BILLETED_BREAK_L = "T51R BILLETED BRAKE L"
    S37C_DL_BREACHER_DEVICE_S = "S-37C DL BREACHER DEVICE S"
    S37C_DL_BREACHER_DEVICE = "S-37C DL BREACHER DEVICE"
    S37C_DL_BREACHER_DEVICE_L = "S-37C DL BREACHER DEVICE L"
    EX01_MATCH_COMPENSATOR = "EX-01 MATCH COMPENSATOR"
    EX01_MATCH_COMPENSATOR_L = "EX-01 MATCH COMPENSATOR L"
    CASUS_BREAK = "CASUS BRAKE"
    CASUS_BREAK_L = "CASUS BREAK L"
    VT7_SPIRITFIRE_SUPPRESSOR = "VT-7 SPIRITFIRE SUPPRESSOR"
    VT7_SPIRITFIRE_SUPPRESSOR_L = "VT-7 SPIRITFIRE SUPPRESSOR L"
    BRUEN_HARMONIC_SUPPRESSOR_L = "BRUENEN HARMONIC SUPPRESSOR L"
    VP27_MINI_BRAKE_S = "VP27 MINI BRAKE S"
    XTEN_RP_40 = "XTEN RP-40"
    FORGE_DX90_F = "FORGE DX90-F"
    SA_SCHALLDAMPFER_99 = "SA SCHALLDAMPFER 99"
    SINGUARD_MKV = "SINGUARD MKV"
    EXF_HUNTRESS_90 = "EXF HUNTRESS 90"
    XTEN_BLACK_KITE = "XTEN BLACK KITE"
    FSS_COVERT_IV = "FSS COVERT IV"
    BRUEN_PENDULUM = "BRUEN PENDULUM"
    AVR_T90_COMP = "AVR-T90 COMP"
    LACERTA_COMPENSATOR = "LACERTA COMPENSATOR"
    XTEN_RAZOR_COMP = "XTEN_RAZOR_COMP"
    XRK_SANDSTORM = "XRK_SANDSTORM"
    BROADHEAD_3DP = "BROADHEAD-3DP"
    SILENTFIRE_XG6 = "SILENTFIRE XG6"
    ECHOLINE_GSX = "ECHOLINE GS-X"
    ZULU_60 = "ZULU-60"
    HARBINGER_D20 = "HARBINGER D20"
    ECHOLESS_80 = "ECHOLESS-80"
    FSS_COVERT_V = "FSS COVERT V"
    GAUGE_9_MONO = "GUAGE-9 MONO"
    NILSOUND_90 = "NILSOUND 90"
    FTAC_DREADNOUGHT = "FTAC DREADNOUGHT"
    FTAC_REAPER = "FTAC REAPER"
    BRUEN_AGENT_90 = "BRUEN AGENT 90"
    TALON_SIXTEEN = "TALON SIXTEEN"
    EXF_RELENTLESS_40 = "EXF RELENTLESS-40"
    BVM_338 = "BVM-338"
    CRONEN_DM338 = "CRONEN DM338"
    SHRED_CP90 = "SHRED CP90"
    XRK_KRAKEN = "XRK KRAKEN"
    TA_CG76 = "TA CG76"
    AP_390_FLASH_HIDER = "AP-390 FLASH HIDER"
    PORTED_DZ38 = "PORTED DZ38"
    DARK_KX50_FLASH_HIDER = "DARK KX50 FLASH HIDER"
    DEMON_HELIX_T7 = "DEMON HELIX T7"
    JAK_BFB = "JAK BFB"
    RF_CROWN_50 = "RF CROWN 50"
    KOMODO_HEAVY = "KOMODO HEAVY"
    XTEN_PORTED_290 = "XTEN PORTED 290"
    FJX_FULCRUM_PRO = "FJX FULCRUM PRO"
    CRONEN_OP44 = "CRONEN OP44"
    FTAC_CASTLE_COMP = "FTAC CASTLE COMP"
    XTEN_HAVOC_90 = "XTEN HAVOC 90"
    SAKIN_TREAD_40 = "SAKIN TREAD-40"
    C400_DOOR_KNOCKER = "C400 DOOR KNOCKER"
    JCZ_390_MUZZLE_DEVICE = "JCZ-390 MUZZLE DEVICE"
    L4R_FLASH_HIDER = "L4R FLASH HIDER"
    CORVUS_SLASH_GEN2 = "CORVUS SLASH GEN. 2"
    CRONEN_MAW_86 = "CRONEN MAW-86"
    DARK_KX30 = "DARK KX30"
    VLK_KOLOSS_FLASH_HIDER = "VLK KOLOSS FLASH HIDER"
    ENDLESS_30_COMPENSATOR = "ENDLESS 30 COMPENSATOR"
    ZEHMN35_COMPENSATED_FLASH_HIDER = "ZEHMN35 COMPENSATED FLASH HIDER"
    HUSHER_65_SILENCER = "HUSHER-65 SILENCER"
    FR_TITAN_SILENCER = "FR TITAN SILENCER"
    POLOARFIRE_S = "POLARFIRE-S"
    ZLR_TALON_5 = "ZLR TALON 5"
    KASTOVIA_DX90 = "KASTOVIA DX90"
    CRONEN_SPDR = "CRONEN SP-DR"
    TEMPUS_GH50 = "TEMPUS GH50"
    TY_LR8 = "TY-LR8"
    LOCKSHOT_KT85 = "LOCKSHOT KT85"
    BRUEN_CUBIC_COMP = "BRUEN CUBIC COMP"
    XRK_KNOCKOUT_BREACH = "XRK KNOCKOUT BREACH"
    SA_LEVELER_55 = "SA LEVELER 55"
    BORE_490 = "BORE-490"
    GL_CLEAR_BREACH = "GL CLAER BREACH"
    TA_HUL_BREACH = "TL HUL-BREACH"
    TA_HUL_BREACH_KL = "TL HUL-BREACH KL"
    SPIRAL_V3p5_FLASH_HIDER = "SPIRAL V3.5 FLASH HIDER"
    FOX_202_FLASH_HIDER = "FOX-202 FLASH HIDER"
    EIGHT_POINT_FLASH_HIDER = "EIGHT-POINT FLASH HIDER"
    TZL_90_V3 = "TZL-90 V3"
    CRONEN_DARK_KX30 = "CRONEN DARK KX30"
    SHIKRA_SILENCER = "SHIKRA SILENCER"

class Optics(Enum):
    NO_MODIFICATIONS = "NO MODIFICATIONS"
    KR_INTLAS_LSJ_3 = "KR INTLAS LSJ-3"
    CRONEN_IRONS = "CRONEN IRONS"
    SLATE_REFLECTOR = "SLATE REFLECTOR"
    JAK_BULLSEYE = "JAK BULLSEYE" 
    SLIMLINE_PRO = "SLIMLINE PRO"
    SZ_MINI = "SZ MINI"
    CRONEN_MINI_DOT = "CRONEN MINI DOT"
    CRONEN_MINI_PRO = "CRONEN MINI PRO"
    SZ_SIGMA_IV_OPTIC = "SZ SIGMA-IV OPTIC"
    SZ_MINITAC_40 = "SZ_MINITAC-40"
    KR_MINITAC_40_RISER = "KR MINITAC-40 RISER"
    QTG_REFLEX_SIGHT = "QTG REFLEX SIGHT"
    CAUCASUS_REFLEX_SIGHT = "CAUCASUS REFLEX SIGHT"
    MK3_REFLECTOR = "MK. 3 REFLECTOR"
    DRAGONS_EYE_OPTIC = "DRAGONS' EYE OPTIC"
    RHINO_REFLEX = "RHINO REFLEX"
    XRK_ON_POINT_OPTIC = "XRK ON-POINT OPTIC"
    AIM_OP_V4 = "AIM OP-V4"
    DF105_REFLEX_SIGHT = "DF105 REFLEX SIGHT"
    MONOCLE_CT90 = "MONOCLE CT90"
    CORVUS_SOL_76 = "CORVUS SOL-76"
    SZ_RECHARGE_DX = "SZ RECHARGE-DX"
    SZ_SRO_7 = "SZ SRO-7"
    CORIO_RE_X_PRO = "CORIO RE-X PRO"
    CHRIOS_HOLO = "CHRIOS HOLO"
    CORIO_ENFORCER_OPTIC = "CORIO ENFORCER OPTIC"
    SZ_LONEWOLF_OPTIC = "SZ LONEWOLF OPTIC"
    KAZAN_HOLO = "KAZAN-HOLO"
    SZ_BATTLE_OPTIC = "SZ BATTLE OPTIC"
    CORVUS_DOWNRANGE_00 = "CORVUS DOWNRANGE-00"
    XTEN_ANGEL_40 = "XTEN ANGEL-40"
    SZ_HOLOTHERM = "SZ HOLOTHERM"
    CORIO_ELT_10_2p5 = "CORIO ELT-10 2.5"
    KR_MORTIS_PRECISION_2p5X = "KR MORTIS PRECISION 2.5X"
    SL_TRUESIGHT_2p5X = "SL TRUESIGHT 2.5X"
    KR_MARAUDER_9_RISER = "KR MARAUDER 9 RISER"
    TOS_NIGHTFALL_2p5X_THERMAL_OPTIC = "TOS NIGHTFALL 2.5X THERMAL OPTIC"
    AOK_4p0X_RQ_9_RECON = "AOK 4.0X RQ-9 RECON"
    TX4_HAVOC = "TX4 HAVOC"
    VLK_4p0_OPTIC = "VLK 4.0 OPTIC"
    SCHLAGER_3p4X = "SCHLAGER 3.4X"
    FORGE_TAC_DELTA_4 = "FORGE TAC DELTA 4"
    CRONEN_ZERO_P_OPTIC = "CRONEN ZERO-P OPTIC"
    SZ_BULLSEYE_OPTIC = "SZ BULLSEYE OPTIC"
    SZ_AGGRESSOR_IR_OPTIC = "SZ AGGRESSOR-IR OPTIC"
    SCHLAGER_NIGHT_VIEW = "SCHLAGER NIGHT VIEW"
    VX350_THERMAL_OPTIC = "VX350 THERMAL OPTIC"
    TEPLO_OP3_SCOPE = "TEPLO-OP3 SCOPE"
    HEINRICHTER_HYBRID_SCOPE = "HEINRICHTER HYBRID SCOPE"
    CORVUS_GHOSTVIEW = "CORVUS GHOSTVIEW"
    DR582_HYBRID_SIGHT = "DR582 HYBRID SIGHT"
    HYBRID_FIREPOINT = "HYBRID FIREPOINT"
    SZ_VOREX_90 = "SZ VOREX-90"
    BPZ40_HYBRID = "BPZ40 HYBRID"
    SZ_OSCAR_9 = "SZ OSCAR-9"
    ANGEL_40_4p8X = "ANGEL-40 4.8X"
    THERMO_OPTIC_X9 = "THERMO-OPTIC X9"
    TEPLO_CLEAR_SHOT = "TEPLO CLEAR SHOT"
    CORIO_CQC_SCOPE = "CORIO CQC SCOPE"
    DAUNT_C80 = "DAUNT-C80"
    FTAC_CHARLIE7 = "FTAC CHARLIE7"
    HMW_20_OPTIC = "HMW-20 OPTIC"
    LUCA_BANDERA_SCOPE = "LUCA BANDERA SCOPE"
    DS_FARSIGHT_11 = "DS FARSIGHT 11"
    RFL_OPTIC_3X = "3X RFL-OPTIC"
    DXS_CORIOLIS_V4 = "DXS CORIOLIS V4"
    LACHMANN_IMPACT_9 = "LACHMANN IMPACT 9"
    SPX_80_6p6X = "SP-X 80 6.6X"
    FTAC_LOCUS_SP = "FTAC LOCUS SP"
    LUCA_FIELD_6 = "LUCA FIELD-6"
    SZ_HEATSOURCE_800 = "SZ HEATSOURCE 800"
    HURRICANE_9_VARIABLE_OPTIC = "HURRICANE 9 VARIABLE OPTIC"
    SZ_ULTRA_11p5X = "SZ ULTRA 11.5X"
    MCPR_300_9p5X = "MCPR-300 9.5X"
    VICTUS_13X = "VICTUS 13X"
    IMPERIUM_12X = "IMPERIUM 12X"
    CARRACK_p300_11X = "CARRACK .300 11X"
    AKALINA_LR_STALK_OPTIC = "AKALINA LR-STALK OPTIC"
    KR_KATT_50_8X_SCOPE = "KR KATT-50 8X SCOPE"
    SHORT_ZOOM_6X_OPTIC = "6X SHORT-ZOOM OPTIC"
    SIGNAL_50_8X = "SIGNAL 50 8X"
    CORIO_13X_VRS = "CORIO 13X VRS"
    CORIO_SZ_HS_800 = "CORIO SZ-HS 800"
    RAPTOR_FVM40 = "RAPTOR-FVM40"
    DREXSOM_PRIME_90 = "DREXSOM PRIME-90"
    ARES_CLEAR_SHOT = "ARES CLEAR SHOT"
    SIGHTMAX_CLEAR_SHOT = "SIGHTMAX CLEAR SHOT"
    VIGILANT_30_C_IRON = "VIGILANT-30 C-IRON"
    LUCA_CANIS_4X_OPTIC = "LUCA CANIS 4X OPTIC"
    CORIO_RV500_OPTIC = "CORIO RV500 OPTIC"
    XTEN_ERX_10_MINI = "XTEN ERX-10 MINI"
    FSS_SPECTRE_MICROTHERM = "FSS SPECTRE MICROTHERM"
    NYDAR_MODEL_2023 = "NYDAR MODEL 2023"
    KR_V4_1X_RISER = "KR V4 1X RISER"
    TPS_INCENDIO_REFLEX = "TPS INCENDIO REFLEX"
    CORIO_EAGLESEYE_2p5X = "CORIO EAGLESEYE 2.5X",
    DEMONIC_CALL = "DEMOIC CALL"
    SZ_HM5_PRECISION_HYBRID_OPTIC = "SZ HM5 PRECISION HYBRID OPTIC"
    JOURNEYMAN_32_SCOPE = "JOURNEYMAN-32 SCOPE"
    CARRACK_6p3X_14X = "6.3X-14X CARRACK"
    HOUNDEYE_INTEGRATED_OPTIC = "HOUNDEYE INTEGRATED OPTIC"
    CRONEN_INTLAS_MSP_12 = "CRONEN INTLAS MSP-12"
    INTLAS_CAS_14 = "INTLAS CAS-14"

class RearGrips(Enum):
    pass

class Stocks(Enum):
    pass

class TriggerActions(Enum):
    pass

class Underbarrels(Enum):
    pass

# class Attachments(Enum):
#     MUZZLES = Muzzles
#     BARRELS = Barrels
#     LASERS = Lasers
#     OPTICS = Optics
#     STOCKS = Stocks
#     COMBS = Combs
#     BOLTS = Bolts
#     REAR_GRIPS = RearGrips
#     TRIGGER_ACTIONS = TriggerActions
#     MAGAZINES = Magazines
#     AMMO_TYPES = AmmoTypes
#     UNDERBARRELS = Underbarrels
#     GUARDS = Guards