"""
Enums to hold names of muzzle attachments.
"""

from enum import Enum, auto
from Weapons import *

invalid_weapons_str = "invalid_weapons"
aftermarket_str = "aftermarket"

class Muzzles(Enum):
    # SVA545, MTZ556, HOLGER556, MCW, DG56, TAQ56, M4, STB556, M13B, ISO HEMLOCK, TEMPUS RAVORBACK, FR AVANCER, 
    # M13C, LACHMANN556, M16, KASTOV74U, KASTOV545
    # CHIMERA HAS NO MUZZLE
    SHADOWSTRIKE_SUPPRESSOR = "SHADOWSTRIKE SUPPRESSOR"
    HMRES_MOD_SUPPRESSOR = "HMRES MOD SUPPRESSOR"
    SONIC_SUPPRESSOR = "SONIC SUPPRESSOR"
    COLOSSUS_SUPPRESSOR = "COLOSSUS SUPPRESSOR"
    BROADHEAD_3DP = "BROADHEAD-3DP"
    SILENTFIRE_XG6 = "SILENTFIRE XG6"
    ECHOLINE_GSX = "ECHOLINE GS-X" #KASTOV762
    ZULU_60 = "ZULU-60" #KASTOV762
    HARBINGER_D20 = "HARBINGER D20"
    ECHOLESS_80 = "ECHOLESS-80"
    FSS_COVERT_V = "FSS COVERT V"
    GAUGE_9_MONO = "GUAGE-9 MONO"
    ELR_BLACKFIRE_COMPENSATOR = "ELR BLACKFIRE COMPENSATOR"
    WRATHGUARD_COMPENSATOR = "WRATHGUARD COMPENSATOR"
    T4LR_SABER_COMPENSATOR = "T4LR SABER COMPENSATOR"
    EX01_MATCH_COMPENSATOR = "EX-01 MATCH COMPENSATOR"
    T51R_BILLETED_BREAK = "T51R BILLETED BRAKE"
    PURIFIER_MUZZLE_BREAK = "PURIFIER MUZZLE BRAKE"
    CASUS_BREAK = "CASUS BRAKE"
    JAK_BFB = "JAK BFB" #KASTOV762
    RF_CROWN_50 = "RF CROWN 50"
    KOMODO_HEAVY = "KOMODO HEAVY"
    XTEN_PORTED_290 = "XTEN PORTED 290"
    FJX_FULCRUM_PRO = "FJX FULCRUM PRO"
    CRONEN_OP44 = "CRONEN OP44"
    FTAC_CASTLE_COMP = "FTAC CASTLE COMP"
    XTEN_HAVOC_90 = "XTEN HAVOC 90"
    SAKIN_TREAD_40 = "SAKIN TREAD-40" #KASTOV762
    S37C_DL_BREACHER_DEVICE = "S-37C DL BREACHER DEVICE"
    C400_DOOR_KNOCKER = "C400 DOOR KNOCKER"
    JCZ_390_MUZZLE_DEVICE = "JCZ-390 MUZZLE DEVICE"
    L4R_FLASH_HIDER = "L4R FLASH HIDER" #KASTOV762
    CORVUS_SLASH_GEN2 = "CORVUS SLASH GEN. 2"
    CRONEN_MAW_86 = "CRONEN MAW-86"
    DARK_KX30 = "DARK KX30"
    VLK_KOLOSS_FLASH_HIDER = "VLK KOLOSS FLASH HIDER"
    VT7_SPIRITFIRE_SUPPRESSOR = "VT-7 SPIRITFIRE SUPPRESSOR"
    MONOLITHIC_SUPPRESSOR = "MONOLITHIC SUPPRESSOR"
    STER45_SKYFURY_COMPENSATOR = "STER45 SKYFURY COMPENSATOR"
    ENDLESS_30_COMPENSATOR = "ENDLESS 30 COMPENSATOR"
    ZEHMN35_COMPENSATED_FLASH_HIDER = "ZEHMN35 COMPENSATED FLASH HIDER" #KASTOV762

    # KASTOV762 ONLY
    VT7_SPIRITFIRE_SUPPRESSOR_L = "VT-7 SPIRITFIRE SUPPRESSOR L"
    HMRES_MOD_SUPPRESSOR_L = "HMRES MOD SUPPRESSOR L"
    BRUENEN_HARMONIC_SUPPRESSOR_L = "BRUENEN HARMONIC SUPPRESSOR L"
    HUSHER_65_SILENCER = "HUSHER-65 SILENCER"
    FR_TITAN_SILENCER = "FR TITAN SILENCER"
    POLOARFIRE_S = "POLARFIRE-S"
    ZLR_TALON_5 = "ZLR TALON 5"
    KASTOVIA_DX90 = "KASTOVIA DX90"
    CRONEN_SPDR = "CRONEN SP-DR"
    STER45_SKYFURY_COMPENSATOR_L = "STER45 SKYFURY COMPENSATOR L"
    ELR_BLACKFIRE_COMPENSATOR_L = "ELR BLACKFIRE COMPENSATOR L"
    T4LR_SABER_COMPENSATOR_L = "T4LR SABER COMPENSATOR L"
    EX01_MATCH_COMPENSATOR_L = "EX-01 MATCH COMPENSATOR L"
    PURIFIER_MUZZLE_BREAK_L = "PURIFIER MUZZLE BRAKE L"
    CASUS_BREAK_L = "CASUS BREAK L"
    TEMPUS_GH50 = "TEMPUS GH50"
    TY_LR8 = "TY-LR8"
    LOCKSHOT_KT85 = "LOCKSHOT KT85"
    SA_LEVELER_55 = "SA LEVELER 55"
    BORE_490 = "BORE-490"
    GL_CLEAR_BREACH = "GL CLAER BREACH"
    TA_HUL_BREACH_KL = "TL HUL-BREACH KL"
    EIGHT_POINT_FLASH_HIDER = "EIGHT-POINT FLASH HIDER"
    TZL_90_V3 = "TZL-90 V3"
    CRONEN_DARK_KX30 = "CRONEN DARK KX30"
    MONOLITHIC_SUPPRESSOR_L = "MONOLITHIC SUPPRESSOR L"
    SONIC_SUPPRESSOR_L = "SONIC SUPPRESSOR L"
    COLOSSUS_SUPPRESSOR_L = "COLOSSUS SUPPRESSOR L"
    WRATHGUARD_COMPENSATOR_L = "WRATHGUARD COMPENSATOR L"
    T51R_BILLETED_BREAK_L = "T51R BILLETED BRAKE L"
    S37C_DL_BREACHER_DEVICE_L = "S-37C DL BREACHER DEVICE L"























