"""
Enums to hold names of muzzle attachments.
"""

from enum import Enum
from Weapons import *

invalid_weapons_str = "invalid_weapons"
aftermarket_str = "aftermarket"

# ACCURATE - AR MeleePrimary MeleeSecondary Launchers done
# CHIMERA AR had no muzzle

class Muzzles(Enum):
    SHADOWSTRIKE_SUPPRESSOR = "SHADOWSTRIKE SUPPRESSOR"
    VT7_SPIRITFIRE_SUPPRESSOR_L = "VT-7 SPIRITFIRE SUPPRESSOR L"
    HMRES_MOD_SUPPRESSOR = "HMRES MOD SUPPRESSOR"
    HMRES_MOD_SUPPRESSOR_L = "HMRES MOD SUPPRESSOR L"
    SONIC_SUPPRESSOR = "SONIC SUPPRESSOR"
    SONIC_SUPPRESSOR_L = "SONIC SUPPRESSOR L"
    COLOSSUS_SUPPRESSOR = "COLOSSUS SUPPRESSOR"
    COLOSSUS_SUPPRESSOR_L = "COLOSSUS SUPPRESSOR L"
    BROADHEAD_3DP = "BROADHEAD-3DP"
    SILENTFIRE_XG6 = "SILENTFIRE XG6"
    ECHOLINE_GSX = "ECHOLINE GS-X"
    ZULU_60 = "ZULU-60"
    HARBINGER_D20 = "HARBINGER D20"
    ECHOLESS_80 = "ECHOLESS-80"
    FSS_COVERT_V = "FSS COVERT V"
    GAUGE_9_MONO = "GUAGE-9 MONO"
    ELR_BLACKFIRE_COMPENSATOR = "ELR BLACKFIRE COMPENSATOR"
    ELR_BLACKFIRE_COMPENSATOR_L = "ELR BLACKFIRE COMPENSATOR L"
    WRATHGUARD_COMPENSATOR = "WRATHGUARD COMPENSATOR"
    WRATHGUARD_COMPENSATOR_L = "WRATHGUARD COMPENSATOR L"
    T4LR_SABER_COMPENSATOR = "T4LR SABER COMPENSATOR"
    T4LR_SABER_COMPENSATOR_L = "T4LR SABER COMPENSATOR L"
    EX01_MATCH_COMPENSATOR = "EX-01 MATCH COMPENSATOR"
    EX01_MATCH_COMPENSATOR_L = "EX-01 MATCH COMPENSATOR L"
    T51R_BILLETED_BREAK = "T51R BILLETED BRAKE"
    T51R_BILLETED_BREAK_L = "T51R BILLETED BRAKE L"
    PURIFIER_MUZZLE_BREAK = "PURIFIER MUZZLE BRAKE"
    PURIFIER_MUZZLE_BREAK_L = "PURIFIER MUZZLE BRAKE L"
    CASUS_BREAK = "CASUS BRAKE"
    CASUS_BREAK_L = "CASUS BREAK L"
    JAK_BFB = "JAK BFB"
    RF_CROWN_50 = "RF CROWN 50"
    KOMODO_HEAVY = "KOMODO HEAVY"
    XTEN_PORTED_290 = "XTEN PORTED 290"
    FJX_FULCRUM_PRO = "FJX FULCRUM PRO"
    CRONEN_OP44 = "CRONEN OP44"
    FTAC_CASTLE_COMP = "FTAC CASTLE COMP"
    XTEN_HAVOC_90 = "XTEN HAVOC 90"
    SAKIN_TREAD_40 = "SAKIN TREAD-40"
    S37C_DL_BREACHER_DEVICE = "S-37C DL BREACHER DEVICE"
    S37C_DL_BREACHER_DEVICE_L = "S-37C DL BREACHER DEVICE L"
    C400_DOOR_KNOCKER = "C400 DOOR KNOCKER"
    JCZ_390_MUZZLE_DEVICE = "JCZ-390 MUZZLE DEVICE"
    L4R_FLASH_HIDER = "L4R FLASH HIDER"
    CORVUS_SLASH_GEN2 = "CORVUS SLASH GEN. 2"
    CRONEN_MAW_86 = "CRONEN MAW-86"
    DARK_KX30 = "DARK KX30"
    VLK_KOLOSS_FLASH_HIDER = "VLK KOLOSS FLASH HIDER"
    VT7_SPIRITFIRE_SUPPRESSOR = "VT-7 SPIRITFIRE SUPPRESSOR"
    MONOLITHIC_SUPPRESSOR = "MONOLITHIC SUPPRESSOR"
    MONOLITHIC_SUPPRESSOR_L = "MONOLITHIC SUPPRESSOR L"
    STER45_SKYFURY_COMPENSATOR = "STER45 SKYFURY COMPENSATOR"
    STER45_SKYFURY_COMPENSATOR_L = "STER45 SKYFURY COMPENSATOR L"
    ENDLESS_30_COMPENSATOR = "ENDLESS 30 COMPENSATOR"
    ZEHMN35_COMPENSATED_FLASH_HIDER = "ZEHMN35 COMPENSATED FLASH HIDER"
    BRUENEN_HARMONIC_SUPPRESSOR_L = "BRUENEN HARMONIC SUPPRESSOR L"
    HUSHER_65_SILENCER = "HUSHER-65 SILENCER"
    FR_TITAN_SILENCER = "FR TITAN SILENCER"
    POLOARFIRE_S = "POLARFIRE-S"
    ZLR_TALON_5 = "ZLR TALON 5"
    KASTOVIA_DX90 = "KASTOVIA DX90"
    CRONEN_SPDR = "CRONEN SP-DR"
    TEMPUS_GH50 = "TEMPUS GH50"
    TY_LR8 = "TY-LR8"
    LOCKSHOT_KT85 = "LOCKSHOT KT85"
    SA_LEVELER_55 = "SA LEVELER 55"
    BORE_490 = "BORE-490"
    GL_CLEAR_BREACH = "GL CLAER BREACH"
    TA_HUL_BREACH_KL = "TL HUL-BREACH KL"
    EIGHT_POINT_FLASH_HIDER = "EIGHT-POINT FLASH HIDER"
    TZL_90_V3 = "TZL-90 V3"
    CRONEN_DARK_KX30 = "CRONEN DARK KX30"


muzzle_dict = {}

muzzle_dict[Muzzles.BORE_490.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.BROADHEAD_3DP.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.BRUENEN_HARMONIC_SUPPRESSOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.C400_DOOR_KNOCKER.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.CASUS_BREAK.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.CASUS_BREAK_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.COLOSSUS_SUPPRESSOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.COLOSSUS_SUPPRESSOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.CORVUS_SLASH_GEN2.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.CRONEN_DARK_KX30.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.CRONEN_MAW_86.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.CRONEN_OP44.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.CRONEN_SPDR.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.DARK_KX30.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.ECHOLESS_80.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.ECHOLINE_GSX.value] = {
    invalid_weapons_str: [ 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.EIGHT_POINT_FLASH_HIDER.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.ELR_BLACKFIRE_COMPENSATOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.ELR_BLACKFIRE_COMPENSATOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.ENDLESS_30_COMPENSATOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.EX01_MATCH_COMPENSATOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.EX01_MATCH_COMPENSATOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.FJX_FULCRUM_PRO.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.FR_TITAN_SILENCER.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.FSS_COVERT_V.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.FTAC_CASTLE_COMP.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.GAUGE_9_MONO.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.GL_CLEAR_BREACH.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.HARBINGER_D20.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.HMRES_MOD_SUPPRESSOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.HMRES_MOD_SUPPRESSOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.HUSHER_65_SILENCER.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.JAK_BFB.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.JCZ_390_MUZZLE_DEVICE.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.KASTOVIA_DX90.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.KOMODO_HEAVY.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.L4R_FLASH_HIDER.value] = {
    invalid_weapons_str: [ 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.LOCKSHOT_KT85.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.MONOLITHIC_SUPPRESSOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.MONOLITHIC_SUPPRESSOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.POLOARFIRE_S.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.PURIFIER_MUZZLE_BREAK.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.PURIFIER_MUZZLE_BREAK_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.RF_CROWN_50.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.S37C_DL_BREACHER_DEVICE.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.S37C_DL_BREACHER_DEVICE_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.SA_LEVELER_55.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.SAKIN_TREAD_40.value] = {
    invalid_weapons_str: [ 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.SHADOWSTRIKE_SUPPRESSOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.SILENTFIRE_XG6.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.SONIC_SUPPRESSOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.SONIC_SUPPRESSOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.STER45_SKYFURY_COMPENSATOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.STER45_SKYFURY_COMPENSATOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.T4LR_SABER_COMPENSATOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.T4LR_SABER_COMPENSATOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.T51R_BILLETED_BREAK.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.T51R_BILLETED_BREAK_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.TA_HUL_BREACH_KL.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.TEMPUS_GH50.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.TY_LR8.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.TZL_90_V3.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.VLK_KOLOSS_FLASH_HIDER.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.VT7_SPIRITFIRE_SUPPRESSOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.VT7_SPIRITFIRE_SUPPRESSOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.WRATHGUARD_COMPENSATOR.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.WRATHGUARD_COMPENSATOR_L.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.XTEN_HAVOC_90.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.XTEN_PORTED_290.value] = {
    invalid_weapons_str: [
        AssaultRifles.KASTOV_762.value, 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.ZEHMN35_COMPENSATED_FLASH_HIDER.value] = {
    invalid_weapons_str: [ 
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.ZLR_TALON_5.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        AssaultRifles.DG_56.value,
        AssaultRifles.FR_556.value,
        AssaultRifles.FR_AVANCER.value,
        AssaultRifles.HOLGER_556.value,
        AssaultRifles.ISO_HEMLOCK.value,
        AssaultRifles.KASTOV_545.value,
        AssaultRifles.KASTOV_74U.value,
        AssaultRifles.LACHMAN_556.value,
        AssaultRifles.M13B.value,
        AssaultRifles.M13C.value,
        AssaultRifles.M16.value,
        AssaultRifles.M4.value,
        AssaultRifles.MCW.value,
        AssaultRifles.MTZ_556.value,
        AssaultRifles.RAM_7.value,
        AssaultRifles.STB_556.value,
        AssaultRifles.SVA_545.value,
        AssaultRifles.TAQ_56.value,
        AssaultRifles.TEMPUS_RAZORBACK.value,
        AssaultRifles.TR_76_GEIST.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}

muzzle_dict[Muzzles.ZULU_60.value] = {
    invalid_weapons_str: [
        AssaultRifles.CHIMERA.value,
        MeleePrimary.RIOT_SHIELD.value,
        MeleeSecondary.COMBAT_KNIFE.value,
        MeleeSecondary.DUAL_KAMAS.value,
        MeleeSecondary.DUAL_KODACHIS.value,
        MeleeSecondary.GUTTER_KNIFE.value,
        MeleeSecondary.KARAMBIT.value,
        MeleeSecondary.PICKAXE.value,
        MeleeSecondary.TONFA.value,
        Launchers.JOKR.value,
        Launchers.PILA.value,
        Launchers.RGL_80.value,
        Launchers.RPG_7.value,
        Launchers.STORMENDER.value,
        Launchers.STRELA_P.value,
    ],
    aftermarket_str: False
}